### ISSUE TITLE
docker-runner pulls out of date image

### ISSUE THREAD

**Issue by franc0is** [stripe/gaps#11]
The stripeoss/gaps image in the docker registry was last updated on 12/10/2014. Since then, a number of bugs have been fixed. Can we get an updated image?

**Comment by gdb** [comment]
Good point — just pushed a new release!

**Comment by bradtgmurray** [comment]
Apologies for commenting on a closed bug, but it doesn't seem like the image has been updated since December if I'm reading the site correctly.

https://registry.hub.docker.com/u/stripeoss/gaps/

![screen shot 2015-05-15 at 1 21 45 pm](https://cloud.githubusercontent.com/assets/33967/7658095/628eef1a-fb05-11e4-968f-8883fe945e18.png)

**Comment by gdb** [comment]
No worries — I think that's just confusing UI (I remember being confused by the same thing at the time). If you look a little higher, you'll see a more recent update stamp:

![](https://www.dropbox.com/s/0zyaa33o75m4heu/Screenshot%202015-05-15%2010.29.42.png?raw=1)

I also fetched the most recent image, and it has the changes I'd pushed. Let me know if you're seeing something different.

**Comment by bradtgmurray** [comment]
Ah, sorry about that. I thought we were running into #7 internally (need to reboot gaps every few days) and I thought we just didn't have the latest images.
