### ISSUE TITLE
stripeoss/gaps Docker image is out of date

### ISSUE THREAD

**Issue by bfirsh** [stripe/gaps#35]
The Docker image for gaps is waay out of date: https://hub.docker.com/r/stripeoss/gaps/

A solution could be to make it an automated build, so it is automatically built off master.

**Comment by antifuchs** [comment]
Oh gosh, thank you for that note. Took me a while to dig up the credentials. I've now built what I hope is the latest merge & pushed that. I'll look into setting up a decent automatic push setup for the `master` branch!

**Comment by antifuchs** [comment]
(Also, I believe this fixes the immediate problem, so I'll close this issue. Thanks again for reporting!)

**Comment by antifuchs** [comment]
OK - thanks again for the suggestion! Since #36 is merged, we now upload the latest master build's docker image as `:latest` (see the build [here](https://travis-ci.org/stripe/gaps/builds/146434571)). We might want to consider releases and tagging those eventually, but for now, I think this will do nicely! (:

**Comment by bfirsh** [comment]
Nice. Thanks! :sparkles:
