### ISSUE TITLE
Gaps keeps crashing with BackendError

### ISSUE THREAD

**Issue by franc0is** [stripe/gaps#9]
I have a test instance of gaps deployed on our internal server for evaluation. It is deployed inside a docker container following the instructions found in the README. Nothing exotic about the configuration.

The application doesn't seem to be able to run more than a couple of hours before it crashes with the following trace:
```
== Sinatra has ended his set (crowd applauds)
/gaps/vendor/bundle/ruby/2.1.0/gems/google-api-client-0.7.1/lib/google/api_client.rb:620:in `block in execute!': Backend Error (Google::APIClient::ServerError)
        from /gaps/vendor/bundle/ruby/2.1.0/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
        from /gaps/vendor/bundle/ruby/2.1.0/gems/retriable-1.4.1/lib/retriable.rb:15:in `retriable'
        from /gaps/vendor/bundle/ruby/2.1.0/gems/google-api-client-0.7.1/lib/google/api_client.rb:595:in `execute!'
        from /gaps/lib/gaps/requestor.rb:160:in `request'
        from /gaps/lib/gaps/requestor.rb:119:in `get_group_settings'
        from /gaps/lib/gaps/db/group.rb:95:in `update_config'
        from /gaps/lib/gaps/db/group.rb:187:in `block (2 levels) in refresh'
        from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/future.rb:27:in `call'
        from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/future.rb:27:in `block in initialize'
        from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/pool.rb:56:in `call'
        from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/pool.rb:56:in `execute'
        from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/pool.rb:384:in `block (2 levels) in spawn_thread'
        from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/pool.rb:351:in `loop'
        from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/pool.rb:351:in `block in spawn_thread'
        from /gaps/vendor/bundle/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
        from /gaps/vendor/bundle/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

**Comment by gdb** [comment]
Well, that doesn't sound like a very positive evaluation so far — sorry to hear that! Is it otherwise working smoothly?

I believe last time we saw this was due to Google issues — I believe that's just a generic 500. If it's just that specific endpoint that's breaking, one potential workaround is to set `populate_group_settings` to false in your site.yaml (which would disable that one call). Is it always that stack trace?

**Comment by franc0is** [comment]
Not great indeed :disappointed:. The functionality is exactly what we need and the tool is performing superbly when it is up.

It is always the same stacktrace, and has been happening a couple hours after I bring it back up without fail.

I'll try disabling `populate_group_settings` in the yaml file. How will that affect user experience?

**Comment by gdb** [comment]
By default, it won't!

Today those settings are only used if you've switched to the `api_scheme` for privacy settings [1], i.e. you are using privacy settings out of Google's database rather than inferring based off the name/JSON tag [2].

Let me know if you see further troubles. With more data, I can probably whip up a patch (to e.g. do some exponential backoff on error rather than just crash).

[1] https://github.com/stripe/gaps/blob/master/lib/gaps/db/group.rb#L159-L160
[2] https://github.com/stripe/gaps#permissions

**Comment by franc0is** [comment]
Ok -- thanks Greg, you've been immensely helpful. I'll make that change and close the issue in a couple of hours provided gaps is still up :)

**Comment by franc0is** [comment]
disabling `populate_group_settings` did the trick. Gaps been up all day. Thanks!
